[package]
name = "core_loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7.3"
anyhow = "1.0"
simplelog = "0.11"
log = "0.4"
directories = "4.0"
